// Vendor the site's web fonts so no render-blocking Google Fonts CSS request
// (or third-party connection) sits on the critical path.
//
// Fetches the css2 stylesheets Google serves to a modern browser, keeps only
// the subsets the site's copy needs (latin everywhere; latin-ext for Lato —
// a testimonial name contains "ă"), downloads the woff2 files to
// client/public/fonts/, and rewrites client/src/shared/styles/fonts.css with
// local @font-face rules plus metric-adjusted local fallbacks (so the
// pre-swap frame keeps the same line breaks and heights).
//
// Run: node scripts/gen-fonts.mjs
import { mkdir, rm, writeFile } from 'fs/promises';

const FONTS_DIR = new URL('../client/public/fonts/', import.meta.url);
const CSS_OUT = new URL('../client/src/shared/styles/fonts.css', import.meta.url);

// Weights/styles mirror actual usage: Inter 300-700 (tokens), Lato 400/700/900
// (Slack testimonials), Newsreader italic 400 (pull quotes), Space Mono
// 400/700 + italic 400 (terminal, code field, 404 maze).
const FAMILIES = [
  {
    // Range query -> Google serves the variable font: one file, weights 300-700
    name: 'Inter',
    query: 'family=Inter:wght@300..700',
    subsets: ['latin'],
  },
  {
    name: 'Lato',
    query: 'family=Lato:wght@400;700;900',
    subsets: ['latin', 'latin-ext'],
  },
  {
    name: 'Newsreader',
    query: 'family=Newsreader:ital,opsz,wght@1,6..72,400',
    subsets: ['latin'],
  },
  {
    name: 'Space Mono',
    query: 'family=Space+Mono:ital,wght@0,400;0,700;1,400',
    subsets: ['latin'],
  },
];

// Send a modern-Chrome UA so Google serves woff2 with unicode-range subsets.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

// Metric-adjusted fallbacks (fontaine/capsize-derived values) so text set in
// the local fallback occupies the same space as the web font, killing the
// swap-induced layout shift for the two families that render real copy.
const FALLBACKS = `
/* Metric-adjusted local fallbacks: same line breaks before and after swap */
@font-face {
  font-family: 'Inter Fallback';
  src: local('Arial');
  size-adjust: 107.12%;
  ascent-override: 90.2%;
  descent-override: 22.48%;
  line-gap-override: 0%;
}

@font-face {
  font-family: 'Lato Fallback';
  src: local('Arial');
  size-adjust: 97.38%;
  ascent-override: 101.32%;
  descent-override: 21.87%;
  line-gap-override: 0%;
}
`;

const slug = (name) => name.toLowerCase().replace(/\s+/g, '-');

/** Parse Google's css2 output into { subset, fontStyle, fontWeight, url, unicodeRange } blocks. */
function parseCss2(css) {
  const blocks = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  for (const [, subset, body] of css.matchAll(re)) {
    const get = (prop) => body.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim();
    blocks.push({
      subset,
      fontStyle: get('font-style'),
      fontWeight: get('font-weight'),
      url: body.match(/url\((\S+?)\)/)?.[1],
      unicodeRange: get('unicode-range'),
    });
  }
  return blocks;
}

await rm(FONTS_DIR, { recursive: true, force: true });
await mkdir(FONTS_DIR, { recursive: true });

let out = `/* ==========================================================================
   Self-hosted web fonts - generated by scripts/gen-fonts.mjs, do not edit
   by hand. Re-run the script to change weights/subsets.
   ========================================================================== */
`;

for (const { name, query, subsets } of FAMILIES) {
  const cssUrl = `https://fonts.googleapis.com/css2?${query}&display=swap`;
  const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text();
  const wanted = parseCss2(css).filter((b) => subsets.includes(b.subset));
  if (!wanted.length) throw new Error(`no ${subsets} blocks found for ${name}`);

  for (const block of wanted) {
    const style = block.fontStyle === 'italic' ? '-italic' : '';
    const ext = block.subset === 'latin' ? '' : `-${block.subset}`;
    const file = `${slug(name)}${style}-${block.fontWeight.replace(/\s+/g, '_')}${ext}.woff2`;

    const buf = Buffer.from(await (await fetch(block.url)).arrayBuffer());
    await writeFile(new URL(file, FONTS_DIR), buf);
    console.log(`wrote fonts/${file}: ${(buf.length / 1024).toFixed(1)} kB`);

    out += `
/* ${name} ${block.fontStyle} ${block.fontWeight} (${block.subset}) */
@font-face {
  font-family: '${name}';
  font-style: ${block.fontStyle};
  font-weight: ${block.fontWeight};
  font-display: swap;
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${block.unicodeRange};
}
`;
  }
}

out += FALLBACKS;
await writeFile(CSS_OUT, out);
console.log(`wrote ${CSS_OUT.pathname}`);
